services:
  fastify:
    build:
      context: ./example-app-be
      dockerfile: ./Dockerfile  # Specify the location of the Dockerfile
    container_name: fastify-app
    working_dir: /app
    volumes:
      - ./example-app-be:/app
    ports:
      - "3000:3000"  # Fastify API port, if you want to expose it directly for debugging
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./example-app-fe/dist:/usr/share/nginx/html # Vue3 SPA static files
    ports:
      - "80:80"  # Expose port 80 for HTTP
    networks:
      - app-network
    depends_on:
      - fastify

networks:
  app-network:
    driver: bridge

